#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#
# invenio-cli-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

OPTS="--force-reinstall --no-cache-dir"

echo "### venv activate:"
. venv/bin/activate

echo "### invenio-cli init:"
invenio-cli init rdm -c v11.0 --no-input

echo "### ls -l my-site:"
ls -l my-site
cd my-site

echo "### invenio-cli install:"
invenio-cli install

echo "### invenio-cli services setup:"
invenio-cli services setup

#pip install $OPTS -r .requirements.txt
#pip freeze
