#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#
# invenio-cli-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

OPTS="--force-reinstall --no-cache-dir"

echo -e "\n### venv activate:"
. venv/bin/activate

echo -e "\n### invenio-cli init:"
invenio-cli init rdm -c v11.0 --no-input

echo -e "\n### ls -l my-site:"
ls -l my-site
cd my-site

echo -e "\n### patch invenio.cfg:"
cat <<EOT >> invenio.cfg

# added for tests:
CSRF_METHODS = []
RECORDS_REST_DEFAULT_CREATE_PERMISSION_FACTORY='invenio_records_rest.utils:allow_all'
RECORDS_REST_DEFAULT_UPDATE_PERMISSION_FACTORY='invenio_records_rest.utils:allow_all'
RECORDS_REST_DEFAULT_DELETE_PERMISSION_FACTORY='invenio_records_rest.utils:allow_all'
EOT

echo -e "\n### invenio-cli install:"
invenio-cli install

echo -e "\n### invenio-cli services setup:"
invenio-cli services setup

echo -e "\n### DEBUG /_cat/indices:"
curl -sX GET "http://127.0.0.1:9200/_cat/indices"
echo -e "\n### DEBUG /my-site-rdmrecords-records/_search:"
curl -sX GET "http://127.0.0.1:9200/my-site-rdmrecords-records/_search" | jq '.'
echo -e "\n### DEBUG /_nodes:"
curl -sX GET "http://127.0.0.1:9200/_nodes" | jq '.'
echo -e "\n### DEBUG Done."


#pip install $OPTS -r .requirements.txt
#pip freeze
