#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#
# invenio-cli-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

OPTS="--force-reinstall --no-cache-dir"

echo "### venv setup for python ver.${PYTHON_VERSION}:"
python${PYTHON_VERSION} -m venv venv

echo "### venv activate:"
. venv/bin/activate

echo "### pip upgrade:"
python3.9 -m pip install --upgrade pip

echo "### install invenio-cli:"
pip install $OPTS invenio-cli
