#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#
# invenio-cli-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

OPTS="--force-reinstall --no-cache-dir"

echo -e "\n### venv setup for python ver.${PYTHON_VERSION}:"
python${PYTHON_VERSION} -m venv venv

echo -e "\n### venv activate:"
. venv/bin/activate
python --version

echo -e "\n### pip upgrade:"
python -m pip install --upgrade pip

echo -e "\n### install invenio-cli:"
pip install $OPTS invenio-cli
